global:
  params:
    x: 1
    y: 2

spring:
  cloud:
    discovery:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        generate_statistics: true

    show-sql: true

management:
  health:
    refresh:
      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/